### ISSUE TITLE
README does not say what the project is

### ISSUE THREAD

**Issue by JeffBezanson** [sixthsense/sixthsense#12]
It would be really helpful to have a sentence or two describing what this is about in the README on github. Clicking the links in the README also does not tell you what it is. It tells you what platforms it runs on, and how many spaces to use when indenting code, but not what it is.

The google code page actually says at the top "sixthsense: An open source project that allows people to create their own SixthSense Device". That is a circular definition. I finally found a definition by clicking through to the home page on google code, but it took a while to find. I'd also suggest fully moving to github, though I imagine that might already be in progress, since the split between the two sites is a bit confusing.

**Comment by Poincare** [comment]
Thanks a lot for your input on this; I've never really realized this. We'll get it fixed immediately.
