### ISSUE TITLE
Errors Building

### ISSUE THREAD

**Issue by emmaleigh** [sixthsense/sixthsense#17]
I am getting a lot of building errors. Wondering if anyone had any ideas what I need to do.

Running Windows 7 Professional x64 (I told Visual Studio to build on x86)
Downloaded Microsoft Visual Studio Express 2012 for Windows Desktop

Here are some of the errors I get:

Warning 1   Could not resolve this reference. Could not locate the assembly "DirectShowLib-2005, Version=2.0.0.0, Culture=neutral, PublicKeyToken=67e7b740cdfc2d3f, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    WUW01
Warning 2   Could not resolve this reference. Could not locate the assembly "FluidKit". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. WUW01
Warning 3   Could not resolve this reference. Could not locate the assembly "NyARToolkitCS, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  WUW01

And 19 more similar warnings

Error   23  The type or namespace name 'TouchlessLib' could not be found (are you missing a using directive or an assembly reference?)  C:\Users\EH\Desktop\sixthsense-master\WUW01\WUW.cs  33  7   WUW01
Error   24  The type or namespace name 'NyARToolkitCSUtils' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\EH\Desktop\sixthsense-master\WUW01\WUW.cs  38  7   WUW01

And 99 more similar errors

**Comment by emmaleigh** [comment]
I guess you are using windows 64 bit....Just follow these step:

1.open the solution in visual studios,in the solution configuration manager define a new platform (x86) and set is as platform for debuging

2.Try to do a full build (this will fail because of missing dlls). this will create a folder x86 in [code\WUW01\bin]

3.copy all dll files from [code\WUW01\bin\debug] to [code\WUW01\bin\x86] these files: DirectShowLib?-2005.dll FluidKit?.dll NyARToolkitCS.dll NyARToolkitCS.sandbox.dll NyARToolkitCSUtils.dll TouchlessLib?.dll VEarthControl.dll WeatherReaderMVC.dll WebCamLib?.dll WPFControl_Album02.dll WPFControl_Clock01.dll WPFControl_Menu02.dll WPFControl_Weather01.dll

4.now back in visual studio remove all the references to the following dlls FluidKit?.dll NyARToolkitCS.dll NyARToolkitCS.sandbox.dll NyARToolkitCSUtils.dll TouchlessLib??.dll VEarthControl.dll WeatherReaderMVC.dll WPFControl_Album02.dll WPFControl_Clock01.dll WPFControl_Menu02.dll WPFControl_Weather01.dll

5.then click on add reference and browse to the x86 folder and add select the following dlls and add them: FluidKit?.dll NyARToolkitCS.dll NyARToolkitCS.sandbox.dll NyARToolkitCSUtils.dll TouchlessLib??.dll VEarthControl.dll WeatherReaderMVC.dll WPFControl_Album02.dll WPFControl_Clock01.dll WPFControl_Menu02.dll WPFControl_Weather01.dll

6.rebuild the solution and you will only receive warnings.

7.now create the follwing folder: [code\WUW01\bin\x86\Debug\Gestures] [code\WUW01\bin\x86\Debug\Inkings] [code\WUW01\bin\x86\Debug\pics] [code\WUW01\bin\x86\Debug\temp]

8.copy the xml files from code\WUW01\bin\Debug\Gestures to code\WUW01\bin\x86\Debug\Gestures

9.copy the DirectShowLib??-2005.dll and WebCamLib??.dll from code\WUW01\bin\Debug\ to code\WUW01\bin\x86\Debug\

10.push the debug button and the app will start

11.you will get an null reference error in WUW_Paint but you can click continue F5 & the app will start with the camrea on and with the config screen, you need to press the new marker button the

**Comment by Poincare** [comment]
So, this is closed?

**Comment by emmaleigh** [comment]
I posted the information that worked for me below. I was building on the 64 bit architecture and needed to copy files. I still have errors with the AxShockwaveFlash object (I think that's what it is) and I am not sure how to resolve that error yet. 

For everything else doing what I posted next was fine. 

Emily

Gmail for iPhone.

**Comment by CreativeWolf** [comment]
Hi @emmaleigh first answer in this link solves the AxShockwaveFlash issue.

http://stackoverflow.com/questions/10685711/vb-net-embedded-flash-object-creates-problems

BTW, I'm on Windows 7 32bit and this is where I am stuck at.

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in WUW01.exe

Additional information: Could not load file or assembly 'NyARToolkitCS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Any pointers, anyone please?

Peace

CW

**Comment by emmaleigh** [comment]
I haven't worked on this recently...sorry! Good luck getting it figured out!

**Comment by Mayurforgit** [comment]
aftervdoing all the steps i am getting  exception errors while runtime
